name: Web Frontend Build

on: [pull_request]

jobs:
  WebBuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build Frontend
      run: |
        cd web/frontend
        npm install
        npm run build
